<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.545">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rafly Putra Darmawan">
<meta name="dcterms.date" content="2024-01-20">

<title>Analisis Pengaruh Kuantitas terhadap Nilai Ekspor Udang Indonesia dalam 10 Tahun Terakhir (2013-2022)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Pengaruh Kuantitas terhadap Nilai Ekspor Udang Indonesia dalam 10 Tahun Terakhir (2013-2022)</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rafly Putra Darmawan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 20, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>Politeknik APP Jakarta</figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Indonesia, sebagai negara kepulauan besar, memiliki kekayaan sumber daya alam yang melimpah, khususnya di sektor perikanan. Salah satu komoditas unggulan yang menjadi andalan ekspor Indonesia adalah udang. Dalam dekade terakhir (2013-2022), Indonesia telah mengalami fluktuasi dalam kuantitas dan nilai ekspor udangnya.</p>
<p>Faktor-faktor seperti perubahan iklim, teknologi budidaya, dan dinamika pasar global telah mempengaruhi produksi dan ekspor udang dari Indonesia. Perubahan iklim dapat mempengaruhi siklus hidup udang dan ketersediaan habitatnya. Teknologi budidaya yang semakin maju memungkinkan peningkatan produksi udang. Sementara itu, dinamika pasar global, seperti permintaan dan harga, juga mempengaruhi nilai ekspor.</p>
<p>Namun, masih ada celah pengetahuan tentang bagaimana kuantitas mempengaruhi nilai ekspor udang Indonesia. Oleh karena itu, penelitian ini bertujuan untuk menganalisis data ekspor udang dari Trade Map selama 10 tahun terakhir. Dengan menggunakan metode analisis statistik, penelitian ini akan mengungkap hubungan antara kuantitas dan nilai ekspor udang.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini dibatasi pada kuantitas dan nilai ekspor udang Indonesia dalam 10 tahun terakhir (2013-2022). Data yang digunakan dalam penelitian ini adalah data yang diperoleh dari Trade Map</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan latar belakang dan ruang lingkup penelitian, maka dapat dirumuskan permasalahan penelitian sebagai berikut:</p>
<ol type="1">
<li>Bagaimana pengaruh kuantitas terhadap nilai ekspor udang Indonesia dalam 10 tahun terakhir (2013-2022)?</li>
</ol>
</section>
<section id="tujuan-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-penelitian"><span class="header-section-number">1.4</span> Tujuan penelitian</h3>
<p>Tujuan dari penelitian ini adalah untuk mengetahui pengaruh kuantitas terhadap nilai ekspor udang Indonesia dalam 10 tahun terakhir (2013-2022).</p>
</section>
<section id="manfaat-penelitian" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="manfaat-penelitian"><span class="header-section-number">1.5</span> manfaat penelitian</h3>
<p>Manfaat dari penelitian ini adalah sebagai berikut:</p>
<p>a. Memberikan informasi mengenai pengaruh kuantitas terhadap nilai ekspor udang Indonesia dalam 10 tahun terakhir (2013-2022).</p>
<p>b. Menjadi bahan pertimbangan bagi pemerintah dan pelaku usaha dalam meningkatkan nilai ekspor udang Indonesia.</p>
</section>
<section id="package" class="level3" data-number="1.6">
<h3 data-number="1.6" class="anchored" data-anchor-id="package"><span class="header-section-number">1.6</span> Package</h3>
<p>Packages yang digunakan dalam laporan ini antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/metopel/tugas"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<section id="daya-saing" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="daya-saing"><span class="header-section-number">2.1</span> Daya Saing</h3>
<p>Daya saing didefinisikan sebagai kemampuan suatu negara, daerah, atau perusahaan untuk bersaing dalam menghasilkan barang atau jasa, dapat diukur melalui konsep Revealed Comparative Advantage (RCA) dan Export Product Dynamics (EPD).”</p>
<p>Teori RCA mengukur keunggulan komparatif suatu komoditas dalam konteks suatu negara.Nilai RCA diperoleh dengan membandingkan pangsa ekspor komoditas tersebut di suatu negara dengan pangsa ekspor komoditas tersebut di dunia. Nilai RCA yang lebih tinggi dari 1 mengindikasikan bahwa negara tersebut memiliki keunggulan komparatif dalam memproduksi komoditas tersebut.</p>
<p>Teori EPD digunakan untuk memahami posisi pangsa pasar suatu komoditas. Posisi pangsa pasar suatu komoditas dapat diidentifikasi berdasarkan dua indikator utama, yaitu peningkatan pangsa pasar ekspor negara dan peningkatan pangsa pasar produk. Analisis EPD mengidentifikasi empat posisi pangsa pasar berbeda, yaitu:</p>
<ul>
<li><p>Rising Star: Komoditas tersebut memiliki keunggulan komparatif dan pangsa pasarnya terus meningkat di pasar global.</p></li>
<li><p>Lost Opportunity: Komoditas tersebut memiliki keunggulan komparatif, tetapi pangsa pasarnya di pasar global justru menurun.</p></li>
<li><p>Falling Star: Komoditas tersebut tidak memiliki keunggulan komparatif, tetapi pangsa pasarnya di pasar global justru meningkat.</p></li>
<li><p>Retreat: Komoditas tersebut tidak memiliki keunggulan komparatif dan pangsa pasarnya di pasar global justru menurun.</p></li>
</ul>
</section>
<section id="faktor-faktor-yang-mempengaruhi-ekspor" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="faktor-faktor-yang-mempengaruhi-ekspor"><span class="header-section-number">2.2</span> Faktor-Faktor yang Mempengaruhi Ekspor</h3>
<p>Ekspor melibatkan segala jenis barang dan jasa yang dijual ke negara lain, termasuk layanan seperti transportasi, permodalan, dan dukungan lainnya yang mendukung proses ekspor. Dinamika ekspor dipicu oleh kelebihan penawaran domestik, di mana harga di dalam negeri cenderung lebih rendah dibandingkan dengan harga di negara lain. Faktor-faktor yang memengaruhi permintaan ekspor, seperti Gross Domestic Product (GDP), nilai tukar riil, dan harga ekspor udang, memberikan dampak signifikan. GDP, sebagai indikator pendapatan rata-rata penduduk suatu negara, mencerminkan tingkat konsumsi dan daya beli terhadap berbagai barang dan jasa. Selain itu, nilai tukar riil mengukur harga mata uang suatu negara terhadap mata uang asing. Dalam konteks ekspor udang, harga ekspor udang dan harga udang di pasar dunia juga memiliki peran krusial dalam menentukan tingkat permintaan ekspor.</p>
</section>
<section id="kerangka-penelitian" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="kerangka-penelitian"><span class="header-section-number">2.3</span> Kerangka Penelitian</h3>
<p>Komoditas udang memegang peranan strategis sebagai penyumbang utama devisa negara dalam subsektor perikanan, dan menjadi sumber pendapatan vital bagi para peternak budi daya udang di Indonesia. Kendati demikian, produktivitas udang di negara ini masih menunjukkan tingkat yang relatif rendah jika dibandingkan dengan produsen besar lainnya seperti Vietnam, Thailand, India, dan Equador. Penelitian ini akan melakukan analisis daya saing dengan menerapkan metode Revealed Comparative Advantage (RCA) dan Export Product Dynamic (EPD). Selain itu, eksplorasi faktor-faktor yang memengaruhi volume ekspor udang Indonesia akan dilakukan, dengan mempertimbangkan variabel seperti GDP, nilai tukar riil, harga ekspor, dan harga udang di pasar dunia.</p>
<p>Hipotesis penelitian didasarkan pada asumsi bahwa nilai RCA untuk udang Indonesia diperkirakan lebih dari satu (RCA &gt; 1), menandakan adanya keunggulan komparatif yang signifikan di pasar internasional. Selain itu, diasumsikan bahwa variabel-variabel seperti GDP, nilai tukar riil, harga ekspor, dan harga udang dunia berpotensi memberikan pengaruh positif terhadap volume ekspor udang Indonesia. Penelitian ini bertujuan untuk memberikan pemahaman yang lebih mendalam terkait dengan dinamika ekspor udang Indonesia dan mengidentifikasi potensi perbaikan dalam meningkatkan daya saingnya di pasar global.</p>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Penelitian ini menggunakan data sekunder yang meliputi periode tahun 2013 hingga 2022. Data tersebut mencakup volume dan nilai ekspor Udang Indonesia, nilai ekspor total dari Indonesia, nilai ekspor udang dunia, nilai ekspor total dunia, nilai tukar rupiah terhadap dolar AS, dan pertumbuhan ekonomi Indonesia. Sumber data berasal dari trade map.</p>
<p>Untuk menganalisis pengaruh kuantitas terhadap nilai ekspor udang. Indonesia digunakan formula sebagai berikut: Laursen dalam Imelda (2017).</p>
<p>RCA = 𝐗𝒊 𝒊𝒏𝒅𝒐𝒏𝒆𝒔𝒊𝒂 ∑ 𝚾𝒊 𝑰𝒏𝒅𝒐𝒏𝒆𝒔𝒊𝒂 / 𝐗𝒊 𝒘𝒐𝒓𝒍𝒅 ∑ 𝚾𝒊 𝒘𝒐𝒓𝒍𝒅</p>
<p>Dimana:</p>
<p>RCA : Revealed Comparative Advantage untuk komoditi i</p>
<p>X𝑖 𝑖𝑛𝑑𝑜𝑛𝑒𝑠𝑖𝑎 : Nilai Ekspor komoditas dari Indonesia</p>
<p>∑ Χ𝑖 𝐼𝑛𝑑𝑜𝑛𝑒𝑠𝑖𝑎 : Nilai ekspor total dari Indonesia</p>
<p>X𝑖 𝑤𝑜𝑟𝑙𝑑 : Nilai ekspor produk dunia</p>
<p>∑ Χ𝑖 𝑤𝑜𝑟𝑙𝑑 : Nilai ekspor total dunia</p>
<p>Apabila nilai RCA yang diperoleh melebihi angka satu, dapat disimpulkan bahwa Indonesia memiliki keunggulan komparatif dalam komoditas terkait dan memiliki daya saing yang kuat. Sebaliknya, jika nilai RCA kurang dari satu, dapat diinterpretasikan bahwa Indonesia tidak memiliki keunggulan komparatif dalam komoditas tersebut atau memiliki daya saing yang lemah. Tingkat keunggulan komparatif semakin meningkat seiring dengan nilai RCA yang lebih tinggi, mencerminkan daya saing yang semakin kuat (Balassa dalam Ratnawati, 2011). Penelitian ini bertujuan untuk menganalisis pengaruh produksi udang, pertumbuhan ekonomi, dan nilai tukar terhadap volume ekspor udang. Indonesia di pasar internasional. menggunakan metode analisis regresi linier berganda dengan pendekatan model Ordinary Least Square (OLS) atau metode kuadrat terkecil biasa, dengan persamaan sebagai berikut:</p>
<p>𝑳𝒐𝒈𝑽𝒌 = 𝜷𝟎 + 𝜷𝟏𝑳𝒐𝒈𝑷𝑲 + 𝜷𝟐𝑳𝒐𝒈𝑲𝑼𝑹𝑺 + 𝜷𝟑𝑳𝒐𝒈𝑷𝑫𝑩 + 𝒆𝒊</p>
<p>Dimana :</p>
<p>𝐿𝑜𝑔𝑉𝑘 :Volume ekspor udang</p>
<p>𝐿𝑜𝑔𝛽0 : Konstanta</p>
<p>𝐿𝑜𝑔𝑃𝐾 : Budi daya udang Indonesia</p>
<p>𝐿𝑜𝑔𝐾𝑈𝑅𝑆 : Nilai tukar rupiah terhadap dollar AS</p>
<p>𝐿𝑜𝑔𝑃𝐷𝐵 : Pertumbuhan ekonomi Indonesia</p>
<p>𝛽1𝛽2 𝛽3 : Koefisien regresi variabel</p>
<p>𝑃𝐾, 𝑃𝐸,𝐾𝑈𝑅𝑆 𝑒𝑖 : Error term</p>
</section>
<section id="data-1" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="data-1"><span class="header-section-number">3.2</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Kuantitas (Tons)</th>
<th>Nilai Ekspor (Ribu USD)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013</td>
<td>109.857</td>
<td>1.181.228</td>
</tr>
<tr class="even">
<td>2014</td>
<td>131.150</td>
<td>1.530.864</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>129.995</td>
<td>1.189.566</td>
</tr>
<tr class="even">
<td>2016</td>
<td>134.495</td>
<td>1.260.253</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>142.300</td>
<td>1.403.571</td>
</tr>
<tr class="even">
<td>2018</td>
<td>148.508</td>
<td>1.345.721</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>149.160</td>
<td>1.269.175</td>
</tr>
<tr class="even">
<td>2020</td>
<td>164.177</td>
<td>1.416.443</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>167.122</td>
<td>1.530.821</td>
</tr>
<tr class="even">
<td>2022</td>
<td>160.681</td>
<td>1.451.665</td>
</tr>
</tbody>
</table>
<p>Sumber : ITC Trade Map</p>
<p>Penelitian ini menggunakan data hubungan antara variabel independen dan variabel lainnya, antara kuantitas ekspor dengan nilai ekspor udang</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.3</span> Metode analisis</h3>
<p>Metode analisis yang diterapkan dalam penelitian ini adalah metode regresi, yang juga dikenal sebagai Ordinary Least Square (OLS). Metode ini digunakan untuk menentukan parameter yang menggambarkan hubungan antara dua variabel. Regresi, atau OLS, memungkinkan identifikasi dan estimasi parameter yang menghubungkan dua variabel dalam suatu konteks analisis. Di samping itu, analisis univariat juga diterapkan dalam penelitian ini, yang merupakan metode analisis data yang menitikberatkan pada satu variabel dependen (variabel tidak bebas) pada setiap objek yang diamati. Pendekatan ini memungkinkan penelitian untuk menjelajahi karakteristik dan hubungan variabel tunggal dalam konteks penelitian ini.</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span></p>
<p>di mana <span class="math inline">\(y_t\)</span> adalah hwy dan <span class="math inline">\(x_t\)</span> adalah cty.</p>
<p>Keterangan : Y disebut juga variabel dependen X disebut juga variabel independent nilai Y dan X kita dapatkan dari data β0 dan β1 disebut parameter. Nilainya kita dapat dari hasil estimasi komputer. μ disebut juga error term / residual. Dia bersifat independen</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Berikut adalah hasil dari plot x dan y, dengan x sebagai kuantitas ekpor udang Indonesia dan y sebagai nilai (value) ekspor udang Indonesia. maka didapatkan plot sebagai berikut :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/metopel/tugas/DataUdang.xlsx"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>Kuantitas, <span class="at">y=</span>NilaiEkspor))<span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">'blue'</span>, <span class="at">size=</span><span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Tabel 1. Plot Terhadap Nilai Ekspor udang Indonesia"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Kuantitas"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Nilai Ekspor"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Sumber: ITC Trade Map"</span>) <span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#impor dataset</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">read_excel</span>(<span class="st">"C:/metopel/tugas/DataUdang.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   Tahun Kuantitas NilaiEkspor
   &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
 1  2013    109857     1181228
 2  2014    131150     1530864
 3  2015    129995     1189566
 4  2016    134495     1260253
 5  2017    142300     1403571
 6  2018    148508     1345721
 7  2019    149160     1269175
 8  2020    164177     1416443
 9  2021    167122     1530821
10  2022    160681     1451665</code></pre>
</div>
</div>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil pengaruh jumlah ekspor dan jumlah impor terhadap pertumbuhan ekonomi diestimasi menggunakan regresi multivariat. Hasilnya ditunjukkan sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/metopel/tugas/DataUdang.xlsx"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data =</span> dat,NilaiEkspor<span class="sc">~</span>Kuantitas)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = NilaiEkspor ~ Kuantitas, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-113612  -50236  -27620   43203  230739 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 6.982e+05  2.864e+05   2.438   0.0407 *
Kuantitas   4.590e+00  1.979e+00   2.319   0.0490 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 106300 on 8 degrees of freedom
Multiple R-squared:  0.4021,    Adjusted R-squared:  0.3274 
F-statistic:  5.38 on 1 and 8 DF,  p-value: 0.04896</code></pre>
</div>
</div>
<p>Tujuan dari penelitian ini adalah untuk mengevaluasi pengaruh dua variabel, yaitu nilai dan kuantitas udang, terhadap variabel dependen nilai ekspor udang Indonesia. Analisis regresi menghasilkan nilai F sebesar 5.38 dengan probabilitas nilai sebesar 0.04896, menunjukkan bahwa kedua variabel tersebut memiliki dampak signifikan terhadap ekspor udang Indonesia selama periode 2013-2022. Koefisien determinasi (R) sebesar 32.74% mengindikasikan sejauh mana variabel independen berkontribusi terhadap variabel dependen.</p>
<p>Selanjutnya, uji parsial dilakukan untuk menilai signifikansi masing-masing variabel independen terhadap variabel dependen. Hasil analisis menunjukkan bahwa harga udang memiliki pengaruh yang signifikan secara parsial terhadap nilai ekspor udang Indonesia, dengan nilai t-hitung sebesar 2.438 dan probabilitas 0.0407 (&lt; 0,1). kuantitas udang secara parsial berpengaruh secara signifikan dengan nilai t-hitung sebesar 2.319 dan probabilitas 0,0490 (&lt; 0,1). Oleh karena itu, dapat disimpulkan bahwa, dalam rentang waktu 2013-2022, kuantitas udang nilai ekspor udang Indonesia, serta harga udang tidak menunjukkan dampak yang signifikan.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Berdasarkan hasil penelitian yang telah dilakukan, dapat disimpulkan bahwa kuantitas udang memiliki pengaruh yang signifikan terhadap nilai ekspor udang Indonesia dalam periode 2013-2022. Hal ini ditunjukkan oleh nilai t-hitung sebesar 2,319 dan probabilitas 0,0490 (&lt; 0,1).</p>
<p>Pengaruh kuantitas udang terhadap nilai ekspor udang dapat dijelaskan sebagai berikut. Semakin banyak udang yang diekspor, maka semakin besar pula nilai ekspor udang tersebut. Hal ini disebabkan oleh beberapa faktor, antara lain:</p>
<ul>
<li><p>Harga udang yang relatif stabil dalam beberapa tahun terakhir.</p></li>
<li><p>Permintaan udang di pasar internasional yang terus meningkat.</p></li>
<li><p>Kebijakan pemerintah yang mendukung peningkatan ekspor udang.</p></li>
</ul>
<p>Namun, pengaruh kuantitas udang terhadap nilai ekspor udang tidak sebesar pengaruh harga udang. Hal ini ditunjukkan oleh nilai t-hitung sebesar 2,438 dan probabilitas 0,0407 (&lt; 0,1).</p>
<p>Pengaruh harga udang terhadap nilai ekspor udang dapat dijelaskan sebagai berikut. Semakin tinggi harga udang, maka semakin besar pula nilai ekspor udang tersebut. Hal ini disebabkan oleh beberapa faktor, antara lain:</p>
<ul>
<li><p>Elastisitas permintaan udang yang relatif inelastis.</p></li>
<li><p>Kurangnya persaingan di pasar internasional.</p></li>
</ul>
<p>Oleh karena itu, pemerintah dan pelaku usaha perlu terus meningkatkan kuantitas produksi udang untuk meningkatkan nilai ekspor udang Indonesia. Selain itu, pemerintah juga perlu melakukan upaya untuk menjaga harga udang agar tetap stabil atau meningkat.</p>
<p>Berikut adalah beberapa rekomendasi kebijakan yang dapat dilakukan oleh pemerintah dan pelaku usaha untuk meningkatkan nilai ekspor udang Indonesia:</p>
<ul>
<li><p>Pemerintah perlu memberikan dukungan kepada para pembudidaya udang untuk meningkatkan produktivitas udang.</p></li>
<li><p>Pemerintah perlu memberikan insentif kepada eksportir udang untuk meningkatkan volume ekspor.</p></li>
<li><p>Pemerintah perlu melakukan promosi dan pemasaran udang Indonesia di pasar internasional.</p></li>
<li><p>Pelaku usaha perlu meningkatkan kualitas dan daya saing udang Indonesia.</p></li>
</ul>
<p>Dengan upaya-upaya tersebut, diharapkan nilai ekspor udang Indonesia dapat terus meningkat dan memberikan kontribusi yang lebih besar bagi perekonomian nasional.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Imelda, R., Nugraheni, I. (2017). Analisis Daya Saing Ekspor Udang Indonesia. Jurnal Ekonomi dan Bisnis Indonesia</p>
<p>ITC Trade Map. (2022). Retrieved January 20, 2024, from https://www.trademap.org/</p>
<p>Sanny, I., et al.&nbsp;(2021). Pengaruh Harga Udang, Nilai Tukar Rupiah, dan Pertumbuhan Ekonomi Terhadap Volume Ekspor Udang Indonesia. Jurnal Ekonomi dan Bisnis Indonesia</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>